app/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("teams/", include("teams.urls", namespace="teams")),
    path("todos/", include("todos.urls", namespace="todos")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from teams.views import TeamListView

app_name = "core"

urlpatterns = [
    path("", TeamListView.as_view(), name="home"),
]

app/teams/urls.py
from django.urls import path
from .views import (
    TeamCreateView,
    TeamDeleteView,
    TeamDetailView,
    join_as_member,
)
from todos.views import create_todo

app_name = "teams"

urlpatterns = [
    path("create/", TeamCreateView.as_view(), name="create"),
    path("<int:pk>/", TeamDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", TeamDeleteView.as_view(), name="delete"),
    path("<int:pk>/members/join/", join_as_member, name="member-join"),
    path("<int:pk>/todos/create/", create_todo, name="create-todo"),
]

app/teams/models.py
from django.db import models
from .managers import CustomMemberManager


class Team(models.Model):
    name = models.CharField("이름", max_length=30, blank=False, null=False)
    description = models.TextField("팀 설명", max_length=255)
    members = models.ManyToManyField(
        "users.User",
        through="teams.TeamMember",
        verbose_name="팀 구성원",
    )

    class Meta:
        verbose_name = "팀"
        verbose_name_plural = "팀들"
        ordering = [
            "id",
        ]

    def __str__(self):
        return self.name


class TeamMember(models.Model):
    user = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="team_members",
        verbose_name="유저",
    )
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, related_name="team_members", verbose_name="팀"
    )
    nickname = models.CharField("별명", max_length=50, null=True)
    is_admin = models.BooleanField(default=False, verbose_name="팀 관리자 여부")
    objects = CustomMemberManager()

    class Meta:
        verbose_name = "구성원"
        verbose_name_plural = "구성원들"
        ordering = ["team", "nickname"]

    def __str__(self):
        return f"{self.team} : {self.user.name}"

app/teams/forms.py
from django.forms import ModelForm
from .models import Team, TeamMember


class CreateTeamForm(ModelForm):
    class Meta:
        model = Team
        exclude = "__all__"

    def save(self, *args, **kwargs):
        team = super().save(commit=False)
        return team


class MemberJoinForm(ModelForm):
    class Meta:
        model = TeamMember
        fields = ("nickname",)

app/teams/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.shortcuts import render, reverse, redirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView
from django.views.generic.list import MultipleObjectMixin
from .decorators import team_adminright_required
from .forms import CreateTeamForm, MemberJoinForm
from .models import Team, TeamMember

admin_rights = [login_required, team_adminright_required]


class TeamListView(ListView):
    model = Team
    template_name = "teams/list.html"
    context_object_name = "team_list"


class TeamCreateView(CreateView, LoginRequiredMixin):
    model = Team
    form_class = CreateTeamForm
    template_name = "teams/create.html"

    def form_valid(self, form):
        user = self.request.user
        team = form.save(commit=False)
        team.save()
        form.save_m2m()
        if user not in team.members.all():
            team.members.add(user)
        return redirect(reverse("teams:detail", args=(team.pk,)))


class TeamDetailView(DetailView, MultipleObjectMixin):
    model = Team
    paginate_by = 12
    paginate_orphans = 6
    template_name = "teams/detail.html"
    context_object_name = "target_team"

    def get_context_data(self, **kwargs):
        object_list = TeamMember.objects.filter(team=self.get_object())
        return super(TeamDetailView, self).get_context_data(
            object_list=object_list, **kwargs
        )


@method_decorator(admin_rights, "get")
@method_decorator(admin_rights, "post")
class TeamDeleteView(DeleteView):
    model = Team
    template_name = "teams/delete.html"


class TeamMemberAddView(CreateView, LoginRequiredMixin):
    model = TeamMember
    template_name = "teams/add_member.html"


@login_required
def join_as_member(request, pk=None):
    if request.method == "POST":
        user = request.user
        team = Team.objects.get(pk=pk)
        form = MemberJoinForm(request.POST)
        if form.is_valid():
            nickname = form.data.get("nickname", None)
            if nickname is not None:
                Team.members.through.objects.create(
                    team=team, user=user, nickname=nickname
                )
                return redirect(reverse("teams:detail", kwargs={"pk": pk}))
        return redirect(reverse("core:home"), kwargs={"error": "form is not valid"})

app/templates/teams/add_member.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock content %}
    

app/templates/teams/create.html
{% extends 'base.html' %}


{% block content %}
{% include 'mixins/form.html' with form=form cta='Create Team!' %}
{% endblock content %}
    

app/templates/teams/detail.html
{% extends 'base.html' %}
{% load on_team %}

{% block content %}
    <div class='w-full h-full flex justify-center'>
        <div>
            <div class="flex justify-between">
                <div>
                    <span class="text-blue-600 text-2xl mt-10">{{target_team.name}} Team</span>
                    <p class="mb-5">{{target_team.description}}</p>
                </div>
                <div class="mr-5 mt-5">
                    <a href="{% url 'teams:create-todo' target_team.pk %}">
                        <i class="fas fa-plus-circle fa-2x"></i>
                    </a>
                </div>
            </div>
            {% on_team target_team as am_i_member %}
            {% if am_i_member %}
            <div class="responsible-list">
                {% for member in object_list %}
                    {% include 'mixins/teams/member_card.html' with member=member %}
                {% endfor %}
                
                
            </div>
            {% if members.has_other_pages %}
                <ul class="flex">
                    {% if members.has_previous %}
                        <li><a href="?page={{members.previous_page_number}}">&laquo;</a></li>
                    {% else %}
                        <li class="hidden"><span>&laquo;</span></li>
                    {% endif %}
                    
                    {% for i in members.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li><span>{{ i }}<span>(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if members.has_next %}
                        <li><a href="?page={{ members.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="hidden"><span>&raquo;</span></li>
                    {% endif %}
                        
                </ul>
            {% endif %}
            {% else %}
                <div class="grid grid-rows-2">
                    <span>이 팀의 구성원이 아니므로 구성원 목록을 볼 수 없습니다.</span>
                    <form method="POST" action="{% url 'teams:member-join' target_team.pk %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="text" name="nickname" id="nickname" required>
                        <input type="submit" value="팀 가입" class="bg-indigo-500 text-white w-14 h-6">
                    </form>
                </div>
            {% endif %}
            <!-- TODO: 멤버일 경우 팀 전체의 TODO를 표시 -->
            <!-- TODO: TODO의 긴급도에 따라 색 정하기 -->
            
                
        </div>
    </div>
{% endblock content %}
    

app/templates/teams/list.html
{% extends 'base.html' %}


{% block content %}
    <div class='w-full text-center'>
        <h1>전체 팀 리스트</h1>
    </div>
    <div class="container mx-auto my-4 px-4 responsible-list">
        {% if team_list %}            
            {% for team in team_list %}
                <a href="{% url 'teams:detail' team.pk %}">
                    {% include 'mixins/teams/card.html' with team=team %}
                </a>
            {% endfor %}
        {% else %}
        {% endif %}        
    </div>
{% endblock content %}
    