app/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("teams/", include("teams.urls", namespace="teams")),
    path("todos/", include("todos.urls", namespace="todos")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from teams.views import TeamListView

app_name = "core"

urlpatterns = [
    path("", TeamListView.as_view(), name="home"),
]

app/teams/urls.py
from django.urls import path
from .views import (
    TeamCreateView,
    TeamDeleteView,
    TeamDetailView,
    join_as_member,
)
from todos.views import create_todo

app_name = "teams"

urlpatterns = [
    path("create/", TeamCreateView.as_view(), name="create"),
    path("<int:pk>/", TeamDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", TeamDeleteView.as_view(), name="delete"),
    path("<int:pk>/members/join/", join_as_member, name="member-join"),
    path("<int:pk>/todos/create/", create_todo, name="create-todo"),
]

app/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    UserCreateView,
    UserDetailView,
    github_login,
    github_callback,
    kakao_login,
    kakao_callback,
)

app_name = "users"

urlpatterns = [
    path("signup/", UserCreateView.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("login/github/", github_login, name="github-login"),
    path("login/github/callback/", github_callback, name="github-callback"),
    path("login/kakao/", kakao_login, name="kakao-login"),
    path("login/kakao/callback/", kakao_callback, name="kakao-callback"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("<int:pk>/", UserDetailView.as_view(), name="detail"),
]

app/templates/partials/footer.html
<footer class="fixed bottom-0 right-0 h-8 w-screen bg-purple-500 text-center">
    <span>&copy; Marco Kang. All rights Reserved.</span>
</footer>

app/templates/partials/header.html
<header class="w-screen h-8 flex bg-purple-400 grid-cols-3">
    <div class="w-full top-4 l-4">
        <a href="{% url 'core:home' %}">
            <span class="material-icons">home</span>
        </a>
    </div>
    <div class="w-full text-center">
        <h2>
            Our To Do
        </h2>
    </div>
    <div class="w-full flex justify-end">
        {% if user.is_authenticated %}
        <div class="grid-cols-2 gap-40 right-4 top-4">
            <a href="{% url 'teams:create' %}">
                <span class="material-icons">group_add</span>
            </a>
            <a href="{% url 'users:detail' user.pk %}">
                <span class="material-icons">account_circle</span>
            </a>
            <a href="{% url 'users:logout' %}">
                <span class="material-icons">logout</span>
            </a>            
        </div>
        {% else%}
        <div class="grid-cols-2 gap-40 p-1">
            <a href="{% url 'users:signup' %}">
                <span class="material-icons">person_add</span>
            </a>
            <a href="{% url 'users:login' %}">
                <span class="material-icons">login</span>
            </a>
        </div>
        {% endif %}
    </div>
</header>